const users = [
  {
    username: "john_doe",
    password: "password",
    name: "John Doe",
    about: "Love hiking and outdoor adventures.",
    profilePicture: "assets/images/john_doe.png",
    status: "online",
    createdAt: new Date("2023-12-08T10:00:00Z"),
  },
  {
    username: "jane_smith",
    password: "password",
    name: "Jane Smith",
    about: "Avid reader and coffee enthusiast.",
    profilePicture: "assets/images/jane_smith.png",
    status: "offline",
    createdAt: new Date("2024-01-15T14:30:00Z"),
  },
  {
    username: "alice_jones",
    password: "password",
    name: "Alice Jones",
    about: "Tech geek and foodie.",
    profilePicture: "assets/images/alice_jones.png",
    status: "offline",
    createdAt: new Date("2024-03-22T08:45:00Z"),
  },
  {
    username: "bob_brown",
    password: "password",
    name: "Bob Brown",
    about: "Musician and artist.",
    profilePicture: "assets/images/bob_brown.png",
    status: "online",
    createdAt: new Date("2024-05-28T16:20:00Z"),
  },
  {
    username: "charlie_clark",
    password: "password",
    name: "Charlie Clark",
    about: "Gamer and streamer.",
    profilePicture: "assets/images/charlie_clark.png",
    status: "online",
    createdAt: new Date("2024-06-01T10:00:00Z"),
  },
  {
    username: "david_wilson",
    password: "password",
    name: "David Wilson",
    about: "Fitness enthusiast.",
    profilePicture: "assets/images/david_wilson.png",
    status: "offline",
    createdAt: new Date("2024-06-05T12:30:00Z"),
  },
  {
    username: "emma_davis",
    password: "password",
    name: "Emma Davis",
    about: "Travel blogger.",
    profilePicture: "assets/images/emma_davis.png",
    status: "online",
    createdAt: new Date("2024-06-10T14:45:00Z"),
  },
  {
    username: "frank_miller",
    password: "password",
    name: "Frank Miller",
    about: "History buff.",
    profilePicture: "assets/images/frank_miller.png",
    status: "offline",
    createdAt: new Date("2024-06-15T16:00:00Z"),
  },
  {
    username: "grace_martin",
    password: "password",
    name: "Grace Martin",
    about: "Photographer.",
    profilePicture: "assets/images/grace_martin.png",
    status: "online",
    createdAt: new Date("2024-06-20T18:15:00Z"),
  },
  {
    username: "harry_thompson",
    password: "password",
    name: "Harry Thompson",
    about: "Chef and food critic.",
    profilePicture: "assets/images/harry_thompson.png",
    status: "offline",
    createdAt: new Date("2024-06-25T20:30:00Z"),
  },
];

export default users;
