name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Make build
        run: npm run build:ui
      - name: Run component tests
        run: npm run test:ui
      - name: Run test database
        run: docker compose -f docker-compose.dev.yml up -d
      - name: Run server tests
        run: npm run test:server
        env:
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
      - name: Run e2e tests
        run: |
          npm run start:test:server &
          npm run dev:ui &
          npm run test:e2e
        env:
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          REDIS_URI: ${{ secrets.REDIS_URI }}
          VITE_IMGBB_API_KEY: ${{ secrets.VITE_IMGBB_API_KEY }}

  deploy:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Trigger backend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl ${{ secrets.RENDER_SERVICE_URL }}
      - name: Trigger frontend deployment
        if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ', '), '#skip') == false }}
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_SERVICE_URL }}
